site_name: PacketTracer Labs
pages:
- Home : index.md
- Test : test.md
- Routing : 
    - Intro : 'routing/intro.md'
    - Static Routing : 'routing/static.md'
    - Default Routing : 'routing/default.md'
    - Dynamic Routing(RIP) : 'routing/rip.md'
    - Dynamic Routing(OSPF) : 'routing/ospf.md'
    - Dynamic Routing(EIGRP) : 'routing/eigrp.md'
theme: readthedocs